token = "DiscordBotToken"
db_host = "PostgresDatabaseHost"
db_name = "PostgresDatabaseName"
db_port = 0
db_user = "PostgresDatabaseUser"
db_password = "PostgresDatabasePassword"
lavalink_node = "139.99.124.43"
lavalink_port = "7784"
lavalink_password = "PasswordIsZoldy"
timeout = 180  # set None if you want 24/7 music
c_appid = "ClientID"
